### ISSUE TITLE
基于深度学习量化中文词汇surprisal

### ISSUE THREAD

**Issue by xiaoyeye668** [DingNLab/workshop#1]
现有的gpt2-chinese-cluecorpussmall预训练模型，token是字符级别，请问下：想获取词汇级别的生成概率，应该如何计算呢~

**Comment by jiajiezou** [comment]
可以考虑基于字级别的概率计算词汇级别的概率。思路如下：P("蝴蝶"|"一只飞舞的")可以等同于P("蝴"|"一只飞舞的") x P("蝶"|"一只飞舞的蝴")。

**Comment by xiaoyeye668** [comment]
非常感谢回复！
再请教下：模型输出output.logits是下个词汇的prediction scores，还需要softmax转换为概率值，这么理解对嘛？
那么如果词汇概率通过字概率连乘~ 因为概率值均[0,1]，词汇序列越长最终得出的词汇概率就会相对地越小~
是否存在不合理呢~

**Comment by jiajiezou** [comment]
1. 需要用softmax转换为概率值：是的。这样也可以确保所有词的概率之和为1。
2. 以先前举过的例子为例，如果模型足够好，那么P("蝶"|"一只飞舞的蝴")将约等于1，所以P("蝴"|"一只飞舞的") x P("蝶"|"一只飞舞的蝴")的概率并不会太小。但模型实际情况如何，可能需要多进行一些测试才能知道。
