### ISSUE TITLE
关于如何使用gpt2计算转移概率及一些其他问题

### ISSUE THREAD

**Issue by caofeizhen** [DingNLab/workshop#2]
您好，我是这个领域的初学者。当我在使用这个代码时，遇到了如下问题，希望可以得到你们的解决与回复：

1.srilm安装并不像代码里直接写的pip就可以使用，不知道是否有相关的教程。
2.由于是该领域的初学者，在使用gpt2计算后续的surprisal和entropy时，代码显示的是与1.2类似。由于缺乏相关的经验实在很难实现，不知道可否对其进行补充，以方便使用。

我知道我的问题可能会占用你们宝贵的时间，带来的不便提前进行抱歉。
由衷地感谢dinglab全体同学的付出，让我们收获了这么多关于大语言模型的知识。

                                                                                                   CFZ

**Comment by jiajiezou** [comment]
1. srilm安装教程请参见https://github.com/zhaoyanpeng/pysrilm
2. 代码部分已增加如何使用gpt2计算surprisal和entropy，请参见新上传的代码；也可参照类似文章的开源代码，如Brennan、Floris Lange、hasson、Evelina Fedorenko等课题组的工作.

如有问题，欢迎继续联系我们。

**Comment by caofeizhen** [comment]
谢谢，辛苦啦！
